### ISSUE TITLE
Schema for conditions

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#112]
https://github.com/aica-technology/api/blob/a0cb3ddd3958bd409fee7ee4d70df2031eaa5a63/schemas/applications/schema/conditions.schema.json#L23

Something does not quite work for the condition schema. I think what's happening with the "oneOf" is that it discards the event property and the `["required": "events"]`. That's what I can say from my tests. I get errors saying that `events` is not allowed, but when I remove `additionalProperties` from the condition_object or the predicate_object, there is no error anymore. So I think we have to rework this a bit, and I tried but can't seem to fix it. Any input appreciated.

@eeberhard @jjenscodee

**Comment by domire8** [comment]
Or maybe what is happening is that we merge two schemas (the one from the event and the condition schema) and both of these schemas have `additionalProperties: false` so they kind of prohibit each other.

**Comment by eeberhard** [comment]
Thanks for making the issue. I was aware of it for quite a while but didn't get around to reporting the issue or looking into it deeply. This part of the schema is very complex because of the recursive nature of conditions. The schema parser used by the frontend and by VSCode (redhat yaml extension) both struggle with this. When I wrote the condition schema originally, I used the parser in CLion which had no issues with the syntax. Ultimately it is probably an issue with the json-schema draft version.

I will have a look at alternative ways of describing the condition syntax that work with all parsers.

**Comment by eeberhard** [comment]
While we are reworking the condition schema, this would be a good time to make `events` property optional and not required. It might even resolve the core issue, but moreover it allows conditions to be defined without them actually triggering events. This can be useful when using conditions through the API or sequences just as a "wait" condition, rather than an event-triggering condition.

**Comment by domire8** [comment]
Yeah, if it wasn't recursive, we could just move the `event` property to the `condition_object`. Agree about making it optional

**Comment by jjenscodee** [comment]
btw, I check the backend/examples/components/test_binary_recorder.yaml because it has the condition and I get lots of errors when opening it. Not sure if it's because this file hasn't been updated for a while? (p.s. I'm linking to application.schema.json locally, not from docs.aica.tech)

Do you have the same result? or the way I test is wrong/not related?
```
Property load_controller is not allowed.
Property interface is not allowed.
Property start is not allowed.
Incorrect type. Expected "Controller Identifier".
Property all is not allowed.
Property events is not allowed.
Incorrect type. Expected "array | Controller Identifier".
```
<img width="1193" alt="Screenshot 2024-01-17 at 13 48 59" src="https://github.com/aica-technology/api/assets/71389754/1b086595-6a06-40f9-ac3f-9d155faa28e8">
<img width="1202" alt="Screenshot 2024-01-17 at 13 49 09" src="https://github.com/aica-technology/api/assets/71389754/ba4123be-6685-453d-aecb-add621e44995">

**Comment by domire8** [comment]
The errors are expected and correct, the app hasn't been updated in a while

**Comment by eeberhard** [comment]
Just to clarify, the errors under `on_start` are "expected" because the example had outdated syntax. But the errors parsing the conditions are "_unexpected_". The condition syntax in the example is correct and the parser is getting confused (the point of this issue)
