### ISSUE TITLE
Update application schema with unified syntax

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#59]
Given all the changes that are tracked by the parent issue, the application syntax needs to be updated too.

**Comment by domire8** [comment]
Here, I'm not sure how you want to do it @eeberhard. On one hand we are now backwards compatible with the syntax that is currently described here. On the other hand we already support the new event syntax. Do you want to
- Tag the current version of this syntax as version 1, or
- Already add the syntax here and have a version 1 where both the old and new syntax are described?

I find option 2 a bit tricky because we'll put in work that is not strictly necessary if we know that version 2 is just around the corner.

**Comment by eeberhard** [comment]
No, I would like to modify the current schema to only describe the new unified syntax, and then tag that as schema version 1

Backwards compatibility with "pre-release" syntax is only to support our existing applications and demos, but should not be officially supported with a version or documentation moving forward.

Note: I would like to use [SchemaVer](https://docs.snowplow.io/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver/) to track json schemas, both because it is semantically different from semver and so as not to get mixed up between API version or python client version. A corresponding GitHub tag might then be `applications-1-0-0`. The specifics around that will be decided and fixed in the final steps of this refactoring work
