### ISSUE TITLE
Track JSON schema versions

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#62]
The JSON schemas should be versioned according to [SchemaVer](https://docs.snowplow.io/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver/), starting at 1-0-0.

But, how to associate specific JSON schemas with a version?

## Option 1

Require the `version` property at the top level of the schema object, and validate it against a const string value.

```json
   "required"   : ["version"],
   "properties" : {
     "version" : { "type":"string", "const":"1-0-0" },
     ...
   }
```

### Pros
- schema version is defined in source, so it doesn't depend on file name / path / URI
- schema version must also be defined in the JSON data itself to be correctly validated (encouraging us to track syntax versions in applications and descriptions, and making it easier to spot outdated apps)

### Cons
- schema version must also be defined in the JSON data itself to be correctly validated (which would require updating existing json data)
- does not support additions or revisions without additional work, e.g. `"enum": ["1-0-0", "1-0-1", "1-1-0"]`

## Option 2

Make a git tag with `<schema_name>_<schema_version>`, e.g. `applications_1-0-0`.

### Pros
- possible to find specific schema versions using tags or URLs 

### Cons
- many tags at the repo level (one for each schema and version), could be confusing if you don't know about the versioning system

## Option 3

Use the top-level `"description"` property of the schema to track the schema version

### Pros
- schema version is defined in source
- super simple, human readable

### Cons
- harder to use for automatic version checking without custom parsing of the schema document
- prevents normal use of description field unless there is some consistent convention (i.e. description always starts with version, semicolon, then text description)

## Option 4

Use the `"$id"` property of the schema to define the base URI with a version identifier

### Pros
- schema version is defined in source
- makes cross-referencing of schemas and subschemas more explicitly version-locked

### Cons
- potential mismatch between specified base URI and actual retrieval URI

**Comment by eeberhard** [comment]
Also to think about: 
 
- Hosting versioned schemas in more easily retrievable place (i.e. rather than permalinking to GitHub source, host on `docs.aica.tech/schemas/...`). This could be part of the workflow in API repository.
- Using bundling tools to compile / flatten schemas and subschemas into one file. This would make hosting and retrieval of specific schemas easier, and may also simplify versioning as a result

**Comment by eeberhard** [comment]
@LouisBrunner @domire8 would be happy for your thoughts around this issue

**Comment by domire8** [comment]
I'm not sure if I can make a meaningful suggestion here, it's a completely new topic for me.

**Comment by LouisBrunner** [comment]
@eeberhard I am not entirely sure how/where this JSON format is used so it's difficult to say. Is this for the API payloads sent between API and frontend? Or to version files stored on the disk read by some other utility?

**Comment by domire8** [comment]
We're talking about [these schemas](https://github.com/aica-technology/api/tree/main/schemas) that define how our application is written and validated

**Comment by LouisBrunner** [comment]
The JSON schemas used to validate the YAML application file?

So we want to version those?

**Comment by domire8** [comment]
Enrico does yes

**Comment by LouisBrunner** [comment]
> Enrico does yes

Fair enough, thanks for the context.

> Option 1

Seems quite painful to manage for metametadata. You also need to change the URL anyway so that means duplicating the version in multiple places, no?

> Option 2

That means we also rely on GitHub's specific URLs for retrieving Git files. It's doable but mixing a bit too many concerns IMO.

> Option 3

Not sure how you would retrieve the version consistently so sounds like a no-go to me.

> Option 4

It does need we need standardized URLs (which is much easier if we do what you propose next), apart from that it's the best solution from the 4.

> * Hosting versioned schemas in more easily retrievable place (i.e. rather than permalinking to GitHub source, host on `docs.aica.tech/schemas/...`). This could be part of the workflow in API repository.

Would be nice to use a service that does this for us, if that exists, otherwise SGTM

> * Using bundling tools to compile / flatten schemas and subschemas into one file. This would make hosting and retrieval of specific schemas easier, and may also simplify versioning as a result

SGTM

**Comment by eeberhard** [comment]
To add some more `<context>`

The [application.schema.json](https://github.com/aica-technology/api/tree/main/schemas/applications/schema/application.schema.json) defines the YAML application syntax that is parsed both by the DSE and the FE graph visualization. 

Currently, there is no versioning, so maintaining the latest application syntax is usually an adhoc process that looks like this:

1. Update the DSE yaml parsing with some new feature (e.g. ability to set parameters on hardware by adding a new property under `hardware: { parameters: [...] }`)
2. Update the JSON schema to indicate that this new property exists (and to document it in the schema metadata)
3. Update the FE typescript declaration generated from the new schema

As a result, the schema is mostly used to document the "hidden logic" of the DSE yaml parser and to generate the typescript interfaces for FE representations of the application. But, there are many features we can unlock if we can version and subsequently host the schema.

(the assumption for some of these is that the respective Dockerfile would pull 

- We can validate an application against the schema in the DSE when an app is loaded through the API
- We can validate applications directly in the FE yaml editor
- The schema also plays nicely with IDEs if people want to edit YAML applications offline
- When we store example apps or user-created apps in a database, we can associate content with the syntax version
  - (as suggested in option 1, the syntax version could also be tracked directly in the application)
- We can track backwards compatibility / migration guides between versions more formally
- Where appropriate for backwards compatibility, we can switch between yaml parsers in DSE or FE based on syntax version (since the result of parsing is to convert the content to an internal representation in memory, we could choose the parser based on syntax version)

I feel that many of those features are not worth implementing / maintaining if the schema is prone to changing in subtle ways without traceability.

`</context>`

My feeling was to go with option 4 + extensions:
- `$id` to define the base URI including the version identifier
  - for example, `/1-0-0/application.schema.json`
- use a bundling tool to flatten all subschemas into one file
- host the flattened schema at a versioned url, which could be a base URL plus the URI from `$id`
  - for example, `docs.aica.tech/schemas/applications/1-0-0/application.schema.json`

Bundling seems necessary (and useful) because the subschemas are currently resolved using `$ref` against the base URI. By setting `$id` to something else, this would break the retrieval URI used to resolve refs. It also avoids needing to host subschemas under the same filestructure.

As long as nothing stands out to you as infeasible or impractical, I will do some tests with `$id` and bundling and see if I can generate a flat file in a workflow. If so, it should hopefully be a simple matter to push that to our docs page with a GitHub action.

**Comment by LouisBrunner** [comment]
So is the `$id` specified in the YAML directly?

**Comment by eeberhard** [comment]
> So is the `$id` specified in the YAML directly?

The `$id` property is specifically metadata in the schema itself, not in the JSON object it describes.
https://json-schema.org/understanding-json-schema/structuring#dollarid

The application YAML does not contain a version identifier, and it wouldn't necessarily need to; to determine the version, we could also valid the yaml against different schema version until there is a match. But we could equally introduce a version property to the yaml application in a later schema which self-describes the major version number of the syntax.

**Comment by LouisBrunner** [comment]
> The $id property is specifically metadata in the schema itself, not in the JSON object it describes.

Then option 4 sounds good.

> to determine the version, we could also valid the yaml against different schema version until there is a match

I don't think that's a good idea, that seems quite error-prone. I think an explicit version (next time there is a breaking change) would be much better.

**Comment by jjenscodee** [comment]
@LouisBrunner @eeberhard I have some questions here:
- I felt a little bit stuck on the workflow to host schema. I tried to put the schema file under build
and deploy -> it worked but the previous version of the schema I deployed was gone.
I also tried to search about it but didn't find something useful (or maybe it's because I didn't use the right keywords when searching). The only way I can think of is to store the previous version also in our github repo or database.


- Another problem I encounter was I broke the doc page last time when I was testing the deploy action. To make the page work, I manually trigger the workflow we have on the `main` branch but:
1. The deploy link from the workflow `pages build and deployment` also change (from https://docs.aica.tech/ to https://aica-technology.github.io/api/). 
<img width="665" alt="Screenshot 2023-11-13 at 09 39 44" src="https://github.com/aica-technology/api/assets/71389754/d55414cd-a601-499f-9deb-ca8ef853fdbf">

2. When access to https://aica-technology.github.io/api/, I still I got errors saying something like "You're using current base url "/" but we suggest to use url "/api/"".
<img width="1441" alt="Screenshot 2023-11-13 at 09 39 39" src="https://github.com/aica-technology/api/assets/71389754/9b7a38d2-f7d2-4825-acf7-65bb40ac250d">

After I change the url in `docusaurus.config.js` , the page can display properly (but the url change). 
I'm not sure why this is happening.

Any ideas?

**Comment by LouisBrunner** [comment]
@jjenscodee

For anything related to the URL or baseURL stuff, see here https://github.com/aica-technology/api/pull/52, IMO it is a GitHub bug. I couldn't find any reason or resource on why it keeps being rolled back.

Regarding the rest, it's true that it's a bit of a pain to manage multiple versions in these workflows. You basically need to deploy a single time with all the versions ready. However there are many ways to resolve this, here are some examples:

 1. As you suggested, we can just add the version in source control
   * Pros: easy to adapt/edit if we find a typo or want to change some wording
   * Cons: repo grows bigger and bigger which might make it difficult to search in (but is that an issue for us?)
 2. When we want to release a new version, we can tag it or change some version file, and then the docs related to the version get stored into a docker image (e.g. `api-json-docs`). When building the whole docs we then pull various images and extract the files. This is similar to how we manage the OpenAPI/Swagger docs right now.
   * Pros: sources and artifacts separated, one canonical version in source control
   * Cons: harder to change existing versions of the docs (however this can be mitigated by having backport branches and allowing tags to be updated in place, in which case we sort of end up with 1. but with potentially many branches instead of many directories)
 3. While it may be doable, I think incremental changes to the docs (i.e. adding a new version inside an already built docusaurus build) is probably not worth it.

**Comment by jjenscodee** [comment]
@eeberhard According to Louis's comments, which methods would you prefer?

**Comment by eeberhard** [comment]
Thanks for the feedback on both sides. Probably for now option 1 is simplest 

The simplest case IMO is option 1, where the versioned, bundled schema is pushed to a specific directory directly on a branch of the repository. This directory would grow as more versions of the schema would be pushed over time. But, deploying to gh-pages would be as simple as copying the whole folder.

The destination branch could be 'main' or something else like 'schemas'. If it's on main then the flat schema files could be directly pushed under the docs directory such that pages deployment doesn't even have to change
