### ISSUE TITLE
Set application from filepath

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#89]
Original discussion [here](https://github.com/JasperTan97/touch_localisation/pull/6#discussion_r1425606623)

As I've mentioned, I'm not sure there is a sensible solution for a helper that can easily detect if a string that ends with `.yaml` should be automatically opened as a file or not.

@eeberhard

**Comment by eeberhard** [comment]
The original discussion is private. I will summarize it here.

## Feature suggestion

A common use of the python API client is to set a YAML application from a file. That currently looks like this:

```python
import yaml
from aica_api.client import AICA


aica = AICA()
my_app_filepath = '/path/to/my_app.yaml'
with open(my_app_filepath, 'r') as file:
    my_app_content = yaml.safe_load(file)
aica.set_application(my_app_content)
```

Potentially, it could be nice to do some logic inside of the `aica.set_application()` function to check if the argument is a filepath, and if the file exists it could read it and send then contact automatically. Then the usage would just be:

```python
from aica_api.client import AICA


aica = AICA()
my_app_filepath = '/path/to/my_app.yaml'
aica.set_application(my_app_filepath)
```

## Discussion

I first suggested looking for a `.yaml` extension.

Dominic's input:

> Detecting a .yaml extension is not good because we might actually want to send a filename to the computer running the app since the app might be on that computer and we happen to know the filepath on that computer (I do that regularly).

I forgot that the actual API endpoint also accepts a path to a file in the running application container. Dominic goes on to suggest:

> What we can do is see if the string ends with .yaml and is to be found on the machine making the api call, then we load it and otherwise we don't. But that might lead to confusing behavior

I think checking if a file exists, then loading and parsing it, and otherwise reverting to sending the raw input argument to the API, allows flexible and compact usage for a very common use-case. The only downside is potentially confusing behavior, but I think this can be avoided just by checking the conditions and printing some logs.

I still think it makes sense as an improvement.
